import { Job, JobMatches, JobMatchWithAction } from './types'

export const mockJobs: Job[] = [
  {
    id: '1',
    jsearch_id: 'jsearch_1',
    title: 'Senior Python Backend Engineer',
    company: 'Tech Corp Inc',
    location: 'San Francisco, CA',
    is_remote: true,
    salary_min: 180000,
    salary_max: 250000,
    description:
      'We are looking for an experienced Python backend engineer to join our growing team. You will work on building scalable APIs using FastAPI and Django.',
    requirements: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'AWS'],
    apply_url: 'https://example.com/apply/1',
    posted_at: '2026-05-15T10:00:00Z',
    match_score: 92,
    matching_skills: ['Python', 'FastAPI', 'PostgreSQL', 'AWS'],
    match_reasons: [
      'Strong Python expertise matches required skills',
      'FastAPI experience aligns perfectly with tech stack',
      'Salary expectations within range',
      'Remote work preference matches',
    ],
    salary_match: true,
    location_match: true,
  },
  {
    id: '2',
    jsearch_id: 'jsearch_2',
    title: 'Full Stack Engineer',
    company: 'StartUp Labs',
    location: 'New York, NY',
    is_remote: false,
    salary_min: 140000,
    salary_max: 200000,
    description:
      'Join our startup as a Full Stack Engineer. We work with React, Node.js, and AWS. Great culture and learning opportunities.',
    requirements: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'AWS'],
    apply_url: 'https://example.com/apply/2',
    posted_at: '2026-05-14T14:30:00Z',
    match_score: 87,
    matching_skills: ['React', 'TypeScript', 'AWS'],
    match_reasons: [
      'TypeScript and React experience valuable',
      'AWS knowledge beneficial',
      'Startup environment offers growth',
      'Salary within expectations',
    ],
    salary_match: true,
    location_match: false,
  },
  {
    id: '3',
    jsearch_id: 'jsearch_3',
    title: 'Machine Learning Engineer',
    company: 'AI Solutions',
    location: 'Remote',
    is_remote: true,
    salary_min: 160000,
    salary_max: 220000,
    description:
      'Build ML models and deploy them to production. Work with Python, TensorFlow, and cloud infrastructure.',
    requirements: ['Python', 'TensorFlow', 'Machine Learning', 'AWS', 'Docker'],
    apply_url: 'https://example.com/apply/3',
    posted_at: '2026-05-13T09:15:00Z',
    match_score: 79,
    matching_skills: ['Python', 'AWS', 'Docker'],
    match_reasons: [
      'Python expertise relevant',
      'Cloud infrastructure knowledge applicable',
      'Remote position matches preference',
      'Good salary alignment',
    ],
    salary_match: true,
    location_match: true,
  },
  {
    id: '4',
    jsearch_id: 'jsearch_4',
    title: 'DevOps Engineer',
    company: 'Enterprise Systems Inc',
    location: 'Boston, MA',
    is_remote: false,
    salary_min: 130000,
    salary_max: 190000,
    description:
      'Manage infrastructure and CI/CD pipelines. Expertise with Kubernetes, Docker, and cloud platforms required.',
    requirements: ['Kubernetes', 'Docker', 'CI/CD', 'AWS', 'Linux'],
    apply_url: 'https://example.com/apply/4',
    posted_at: '2026-05-12T11:45:00Z',
    match_score: 75,
    matching_skills: ['Docker', 'AWS', 'Linux'],
    match_reasons: [
      'Docker and AWS experience relevant',
      'Infrastructure knowledge applicable',
      'Salary competitive',
      'Location requires relocation',
    ],
    salary_match: true,
    location_match: false,
  },
  {
    id: '5',
    jsearch_id: 'jsearch_5',
    title: 'Frontend Engineer (React)',
    company: 'Creative Digital',
    location: 'Los Angeles, CA',
    is_remote: true,
    salary_min: 120000,
    salary_max: 180000,
    description:
      'Build beautiful user interfaces with React. Work with designers and backend engineers to create amazing products.',
    requirements: ['React', 'TypeScript', 'CSS', 'HTML', 'JavaScript'],
    apply_url: 'https://example.com/apply/5',
    posted_at: '2026-05-11T16:20:00Z',
    match_score: 82,
    matching_skills: ['React', 'TypeScript', 'JavaScript'],
    match_reasons: [
      'Strong React and TypeScript skills',
      'JavaScript expertise matches',
      'Remote work available',
      'Salary in acceptable range',
    ],
    salary_match: true,
    location_match: true,
  },
]

export const mockJobMatches: JobMatchWithAction = {
  match_id: '1',
  job: mockJobs[0],
  match_score: 92,
  match_reasons: mockJobs[0].match_reasons || [],
  user_action: undefined,
  created_at: new Date().toISOString(),
}

export function getMockJobMatches(limit: number = 20, offset: number = 0): JobMatches {
  return {
    total: mockJobs.length,
    limit,
    offset,
    matches: mockJobs.slice(offset, offset + limit).map((job, idx) => ({
      match_id: `match_${idx}`,
      job,
      match_score: job.match_score || 80,
      match_reasons: job.match_reasons || [],
      user_action: undefined,
      created_at: new Date().toISOString(),
    })),
  }
}
